### PR TITLE
V2 messaging = Brain Storming

### PR DESCRIPTION
**Pull request by dtolb**
### ⚠️Do not merge

Make sure you've checked off all these things before submitting:

- [ ] This pull request contains 100% test coverage.
- [ ] This pull request is completely documented. All available fields are listed in the docs with description.
- [ ] Each public facing method should include at least one example using said method.

### CODE REVIEW

**Comment by jmulford-bw** [comment]
I'm personally not a huge fan of having non helper-library code in the __init__.py file. I'd rather see these classes in their own separate files.

What's your thoughts on having this be a separate package similar to how we did with v2m for java?

The functionality is fine though, I like this idea

**Comment by dtolb** [comment]
We can move the files out of init.py, that's how I think they used to be structured. 

I'm not personally a fan of the multiple SDK model we did for java. Isn't this mostly already structured around that tho with the various clients?

```python
from bandwidth import messaging, voice, account
messaging_api = messaging.Client('u-user', 't-token', 's-secret')
voice_api = voice.Client('u-user', 't-token', 's-secret')
account_api = account.Client('u-user', 't-token', 's-secret')
```

Where each team could manage their own package?

**Comment by jmulford-bw** [comment]
True, but how would someone using this SDK distinguish between V1M and V2M?

**Comment by dtolb** [comment]
Right now it keys off of [API Version](https://github.com/Bandwidth/python-bandwidth/pull/30/files#diff-f2cd10d959e0f03bddb11dc62ebff666R39).

```python
messaging_api = bandwidth.client('messaging', 'u-user', 't-token', 's-secret', api_version=2)
```

I was thinking we could major version bump this one, make v2 the default messaging and require v1 to be explicitly assigned.

**Comment by jmulford-bw** [comment]
I've been sitting on this a bit. If you want to go with the multiple client module, I think V2 messaging should be its own client and not be built off of the V1 client. My main reason is simply due to the fact that number ordering and account creation will reside in the dashboard for V2M, and simply changing "v1" to "v2" in the URL dynamically will wrongly expose API functions that an exclusively V2 customer won't have access to

**Comment by dtolb** [comment]
That model as described is how the `messaging_api = bandwidth.client('messaging', 'u-user', 't-token', 's-secret', api_version=2)` would work. It would create it's own _v2_ client.

See the [init.py](https://github.com/Bandwidth/python-bandwidth/blob/v2-messaging/bandwidth/__init__.py#L39) for this branch. 

I agree with the thought, it shouldn't be a simple update from `https://.../v1/...` to `https://.../v2/...`

**Comment by jmulford-bw** [comment]
Gotcha! Yeah that makes sense

**Comment by lukeburden** [comment]
Any movement on this one folks? I'm just moving some of our transactional SMS over to Bandwidth and am keen to start on v2 (using this python lib) to avoid an imminent migration.

**Comment by dtolb** [comment]
> Any movement on this one folks? I'm just moving some of our transactional SMS over to Bandwidth and am keen to start on v2 (using this python lib) to avoid an imminent migration.

@lukeburden can you reach out to dx@bandwidth.com ! We're actively working on updates.

Thanks!

**Pull request closed without merging**
